# Generated by Django 5.0.7 on 2024-08-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appulrico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profesion',
            new_name='especialidad',
        ),
    ]
