# Generated by Django 5.0.7 on 2024-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appulrico', '0002_rename_profesion_profesor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default=31587562, max_length=100),
            preserve_default=False,
        ),
    ]
